### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by lwrage** [Xerxekyran/SMTL#1]
I would like to see if I can use SMTL for a project and maybe reuse and modify the source code along the way. However, I can't use it without a license (https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license). Could you add a license that allows others to use the code, please?

**Comment by Xerxekyran** [comment]
Hi Lutz Wrage,

I just added the MIT license to the project. So you are free to use and modify it as long as you provide attribution back to me.  I am glad to see that it may be usefull to others as well and I am interested in your results, if you want to share them. 

Best Regards
Lars George
